spring.application.name=SpringAIDemo

spring.ai.openai.api-key=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
spring.ai.anthropic.api-key=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

spring.ai.ollama.chat.options.model=deepseek-r1:1.5b
